#include <libuma/command/original.h>

uma_command_info uma_command_original[] = {
	{0xA1, "PING", "Send a 4 bytes payload to mooltipass and it will echo it back"},
	{0xA2, "VERSION_GET", "Retrieve mooltipass firmware version"},
	{0xA3, "CONTEXT_SET", ""},
	{0xA4, "LOGIN_GET", ""},
	{0xA5, "PASSWORD_GET", ""},
	{0xA6, "LOGIN_SET", ""},
	{0xA7, "PASSWORD_SET", ""},
	{0xA8, "CHECK_PASSWORD", ""},
	{0xA9, "CONTEXT_ADD", ""},
	{0xAA, "BOOTLOADER_PWD_SET", ""},
	{0xAB, "JUMP_TO_BOOTLOADER", ""},
	{0xAC, "RANDOM_NUMBER_GET", ""},
	{0xAD, "MEMORYMGMT_ENTER", ""},
	{0xAE, "IMPORT_MEDIA_START", ""},
	{0xAF, "IMPORT_MEDIA", ""},
	{0xB0, "IMPORT_MEDIA_END", ""},
	{0xB1, "MOOLTIPASS_PARM_SET", ""},
	{0xB2, "MOOLTIPASS_PARM_GET", ""},
	{0xB3, "CARD_RESET", ""},
	{0xB4, "READ_CARD_CREDS", ""},
	{0xB5, "RESERVED", ""},
	{0xB6, "CARD_LOGIN_SET", ""},
	{0xB7, "CARD_PASS_SET", ""},
	{0xB8, "UNKNOWN_CARD_ADD", ""},
	{0xB9, "STATUS_GET", ""},
	{0xBA, "FUNCTIONAL_TEST_RES", ""},
	{0xBB, "DATE_SET", ""},
	{0xBC, "UID_SET", ""},
	{0xBD, "UID_GET", ""},
	{0xBE, "DATA_SERVICE_SET", ""},
	{0xBF, "DATA_SERVICE_ADD", ""},
	{0xC0, "WRITE_32B_IN_DN", ""},
	{0xC1, "READ_32B_IN_DN", ""},
	{0xC2, "CUR_CARD_CPZ_GET", ""},
	{0xC3, "REQUEST_CANCEL", ""},
	{0xC4, "PLEASE_RETRY", ""},
	{0xC5, "FLASH_NODE_READ", ""},
	{0xC6, "FLASH_NODE_WRITE", ""},
	{0xC7, "FAVORITE_GET", ""},
	{0xC8, "FAVORITE_SET", ""},
	{0xC9, "STARTING_PARENT_GET", ""},
	{0xCA, "STARTING_PARENT_SET", ""},
	{0xCB, "CTRVALUE_GET", ""},
	{0xCC, "CTRVALUE_SET", ""},
	{0xCD, "CARD_CPZ_CTR_ADD", ""},
	{0xCE, "CARD_CPZ_CTR_GET", ""},
	{0xCF, "CARD_CPZ_CTR_PACKET", ""},
	{0xD0, "FREE_SLOTS_ADDR_GET", ""},
	{0xD1, "DN_START_PARENT_GET", ""},
	{0xD2, "DN_START_PARENT_SET", ""},
	{0xD3, "MEMORYMGMT_LEAVE", ""},
	{0xD4, "USER_CHANGE_NB_SET", ""},
	{0xD5, "DESCRIPTION_GET", ""},
	{0xD6, "USER_CHANGE_NB_GET", ""},
	{0xD7, "FREE_NB_USR_SLT_GET", ""},
	{0xD8, "DESCRIPTION_SET", ""},
	{0xD9, "DEVICE_LOCK", ""},
	{0xDA, "MINI_SERIAL_GET", ""},
	{0xDB, "UNLOCK_WITH_PIN", ""},
};

const size_t uma_command_original_size = sizeof(uma_command_original) / sizeof(uma_command_info);
