
#ifndef UMA_DEVICE_USB_DEFINITION
#define UMA_DEVICE_USB_DEFINITION

#define MOOLTIPASS_VENDOR_ID  0x16D0  //< Vendor ID
#define MOOLTIPASS_PRODUCT_ID 0x09A0  //< Product ID (from MCS)

#endif //UMA_DEVICE_USB_DEFINITION
